@startuml

actor User
entity Koshelek
database DB

User -> Koshelek : Add friend
Koshelek -> DB : register user id
Koshelek -> User : Short greeting
Koshelek -> User : Q."Use week budget?"
User -> Koshelek : y/n
Koshelek -> DB : set week flag
Koshelek -> User : Q."Use month budget?"
User -> Koshelek : y/n
Koshelek -> DB : set month flag


@enduml